apiVersion: v1
kind: Pod
metadata:
  name: kubia-livenss-initial-delay
spec:
  containers:
  - name: kubia
    image: luksa/kubia-unhealthy
    livenessProbe:
      httpGet:
        port: 8080
        path: /
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 10

